### ISSUE TITLE
Editing method should follow the README

### ISSUE THREAD

**Issue by larseggert** [ietf/tao#47]
Specifically:
> The main branch always has the current working copy. Pull requests should be based off main and are merged into main when they are accepted.

>When the current tip of main is published to the IETF website, it is pushed to the published branch, and a new tag in YYYY-MM-DD format is created based on the publication date.

>Comparing the main and published branches hence always shows all currently unpublished differences.

This would **really** make IESG reviews easier, because we could look at the diff between these branches.

**Comment by nllz** [comment]
Done!
