### ISSUE TITLE
Section 3.12.2 seems to be trying to deter network operator participation

### ISSUE THREAD

**Issue by JayDaley** [ietf/tao#57]
Section 3.12.2 starts with 

> "Running a network is hard enough without having to grapple with new protocols or new versions of the protocols with which you are already dealing."

This is more of a deterrent than a welcoming statement.  The second paragraph has a lot of good reasons for network operators to participate, which should be emphasised.

**Comment by nllz** [comment]
Hi @JayDaley - thanks for the issue! Could you let me know if you think https://github.com/ietf/tao/pull/60 addresses the issue sufficiently? Thanks!
