### ISSUE TITLE
Should we restructure the Tao?

### ISSUE THREAD

**Issue by mirjak** [ietf/tao#6]
I'm wondering if it would make more sense for newcomers to kind of reverse the order od the doc, still starting with the mission but then talk about how to contributie, the meeting, wg sessions, mailing lists, and the at the end the more formal stuff like IESG and ISOC. I didn't check if that is an easy change in the sense that currently later sections might assume pre-knowledge from previous sections. However, I guess often people might anyway only read parts of the Tao and therefore working with forward references if really needed shouldn't be too bad

**Comment by nllz** [comment]
I like this proposal, and I think we should restructure the Tao.

For this revision of the Tao is was my intention to remove everything that is wrong and correct that, and for a next version to think of a bit more thorough overhaul. This could also help spur the discussion about the Tao and use it as a living document, as it was intended when it stopped being and RFC and became a website (RFC6722).

If we think we should rather do all changes at once, then I don't see why we won't publish the Tao as RFC again, but that might be a discussion for another time.

**Comment by nllz** [comment]
Addressed with significant changes in newly published version approved by the IESG
